/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_youngqq_testjni_JNIDemo3 */

#ifndef _Included_cn_youngqq_testjni_JNIDemo3
#define _Included_cn_youngqq_testjni_JNIDemo3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_youngqq_testjni_JNIDemo3
 * Method:    GetSum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_cn_youngqq_testjni_JNIDemo3_GetSum
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
