/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_youngqq_testjni_JNIDemo2 */

#ifndef _Included_cn_youngqq_testjni_JNIDemo2
#define _Included_cn_youngqq_testjni_JNIDemo2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_youngqq_testjni_JNIDemo2
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_youngqq_testjni_JNIDemo2_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
