/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_youngqq_testjni_JNIDemo4 */

#ifndef _Included_cn_youngqq_testjni_JNIDemo4
#define _Included_cn_youngqq_testjni_JNIDemo4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_youngqq_testjni_JNIDemo4
 * Method:    initInt2DArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_cn_youngqq_testjni_JNIDemo4_initInt2DArray
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
