/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_youngqq_testjni_JNIDemo1 */

#ifndef _Included_cn_youngqq_testjni_JNIDemo1
#define _Included_cn_youngqq_testjni_JNIDemo1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_youngqq_testjni_JNIDemo1
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_youngqq_testjni_JNIDemo1_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
